stages:
  - build
  - deploy

variables:
  IMAGE_NAME: aestoolscelad/flask-app-baha:v4.0
  DOCKER_BUILDKIT: "1"
  COMPOSE_DOCKER_CLI_BUILD: "1"
  GIT_STRATEGY: clone
  GIT_DEPTH: 1
  GIT_CLEAN_FLAGS: none

before_script:
  - git config --system core.longpaths true
  - git config --global core.longpaths true
  - git config --global --add safe.directory "$CI_PROJECT_DIR"


build:
  stage: build
  tags:
    - windows-runner
  script:
    - docker system prune -f
    - docker compose build
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[build\]/'
      when: on_success
    - when: never

deploy:
  stage: deploy
  tags:
    - windows-runner
  script:
    - pwsh --version
    - docker compose down
    - docker compose up -d --remove-orphans
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[deploy\]/'
      when: on_success
    - when: never
