stages:
  - build
  - push
  - deploy

variables:
  IMAGE_NAME: aestoolscelad/flask-app-baha:v4.0
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  COMPOSE_PROJECT_NAME: flask-app-baha  # Prevent naming conflicts

build:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  script:
    - docker info
    - docker system prune -f --all
    - docker build -t $IMAGE_NAME .
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push "$IMAGE_NAME"
  artifacts:
    paths:
      - docker-compose.yml
    expire_in: 1 hour

push:
  stage: push
  image: docker:24.0
  services:
    - docker:24.0-dind
  needs: ["build"]
  script:
    - echo "Image already pushed during build stage"

deploy:
  stage: deploy
  tags:
    - LocalRunner
  needs: ["push"]
  before_script:
    - apt-get update && apt-get install -y docker-compose-plugin || true
    - docker --version
    - docker compose version
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker compose down --remove-orphans --timeout 30 || true
    - docker compose pull
    - docker compose up -d --build --remove-orphans
    - docker compose ps
    - docker compose logs --tail=20