stages:
  - build
  - push
  - deploy

variables:
  IMAGE_NAME: aestoolscelad/flask-app-baha:v4.0
  DOCKER_BUILDKIT: "1"  # Active BuildKit si disponible
  PIP_CACHE_DIR: "C:/gitlab-runner/builds/pip_cache"  # Pour cache pip dans Docker

cache:
  key: pip-cache
  paths:
    - pip_cache/

build:
  stage: build
  tags:
    - windows-runner
  script:
    - echo "Build stage on Windows"
    - docker version
    - docker system prune -f
    - docker build --build-arg PIP_CACHE_DIR=%PIP_CACHE_DIR% --progress=plain -t $env:IMAGE_NAME .
    - echo $env:DOCKERHUB_PASSWORD | docker login -u $env:DOCKERHUB_USERNAME --password-stdin
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[build\]/'
      when: on_success
    - when: never

deploy:
  stage: deploy
  tags:
    - windows-runner
  script:
    - echo "Deploy stage on Windows"
    - echo "Username: $env:DOCKERHUB_USERNAME"
    - echo "Password Length: $($env:DOCKERHUB_PASSWORD.Length)"
    - if ([string]::IsNullOrEmpty($env:DOCKERHUB_PASSWORD)) { echo "❌ Password is empty" }
    - echo $env:DOCKERHUB_PASSWORD | docker login -u $env:DOCKERHUB_USERNAME --password-stdin
    - docker version
    - docker compose down
    - docker compose up -d --remove-orphans
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[deploy\]/'
      when: on_success
