stages:
  - build
  - deploy

variables:
  IMAGE_NAME: aestoolscelad/flask-app-baha:v4.0
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

build:
  stage: build
  tags:
    - windows-runner
  script:
    - pwsh --version
    - echo "%DOCKERHUB_PASSWORD%" | docker login -u "%DOCKERHUB_USERNAME%" --password-stdin

    - docker system prune -f
    - docker compose build --build-arg BUILDKIT_INLINE_CACHE=1
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[build\]/'
      when: on_success
    - when: never

deploy:
  stage: deploy
  tags:
    - windows-runner
  script:
    - pwsh --version

    - echo "%DOCKERHUB_PASSWORD%" | docker login -u "%DOCKERHUB_USERNAME%" --password-stdin

    - docker compose down
    - docker compose up -d --remove-orphans
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[deploy\]/'
      when: on_success
    - when: never
