build:
  stage: build
  image: docker:latest
  tags:
    - LocalRunner
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  before_script:
    - apk add --no-cache docker-cli docker-compose
  script:
    - docker info
    - docker-compose build
