stages:
  - build
  - push
  - deploy

variables:
  IMAGE_NAME: aestoolscelad/flask-app-baha:v4.0
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker:latest
  tags:
    - LocalRunner2
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false"]
      variables:
        DOCKER_TLS_CERTDIR: ""
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - apk add --no-cache docker-cli
    - docker info

  script:
    - docker system prune -f
    - docker compose build
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    #- docker compose push
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[build\]/'
      when: on_success
    - when: never

deploy:
  stage: deploy
  image: docker:latest
  tags:
    - LocalRunner2
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false"]
      variables:
        DOCKER_TLS_CERTDIR: ""
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_TLS_CERTDIR: ""


  before_script:
    - apk add --no-cache docker-cli
    - docker info

  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker compose down
    #- docker pull "$IMAGE_NAME"
    - docker compose up -d --remove-orphans
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[deploy\]/'
      when: on_success



