stages:
  - build
  - push
  - deploy

variables:
  IMAGE_NAME: aestoolscelad/flask-app-baha:v4.0
  DOCKER_BUILDKIT: "1"
  PIP_CACHE_DIR: "C:/gitlab-runner/builds/pip_cache"

cache:
  key: pip-cache
  paths:
    - pip_cache/

build:
  stage: build
  tags:
    - windows-runner
  script:
    - echo "Build stage on Windows"
    - docker version
    - docker system prune -f
    - docker build --build-arg PIP_CACHE_DIR=%PIP_CACHE_DIR% --progress=plain -t $env:IMAGE_NAME .

    # Enhanced credential validation and debugging
    - $trimmedPassword = $env:DOCKERHUB_PASSWORD.Trim()
    - echo "Trimmed password length: $($trimmedPassword.Length)"
    - $trimmedPassword | docker login -u $env:DOCKERHUB_USERNAME --password-stdin || (
        Write-Host "❌ Docker login failed";
        exit 1
      )
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[build\]/'
      when: on_success
    - when: never

deploy:
  stage: deploy
  tags:
    - windows-runner
  script:
    - echo "Deploy stage on Windows"
    - docker version

    # Use trimmed credentials for login
    - $trimmedPassword = $env:DOCKERHUB_PASSWORD.Trim()
    - $trimmedPassword | docker login -u $env:DOCKERHUB_USERNAME --password-stdin || (
        Write-Host "❌ Docker login failed";
        exit 1
      )

    - docker compose down
    - docker compose up -d --remove-orphans
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[deploy\]/'
      when: on_success