stages:
  - build
  - deploy

variables:
  IMAGE_NAME: aestoolscelad/flask-app-baha:v4.0
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: "1"

build:
  stage: build
  image: docker:24.0
  services:
    - name: docker:dind
      command: ["--tlsverify", "--tlscacert=/certs/client/ca.pem", "--tlscert=/certs/client/cert.pem", "--tlskey=/certs/client/key.pem"]
  before_script:
    - echo $CI_DOCKER_HUB_PASSWORD | docker login -u $CI_DOCKER_HUB_USER --password-stdin
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  tags:
    - docker
  script:
    - echo $CI_DOCKER_HUB_PASSWORD | docker login -u $CI_DOCKER_HUB_USER --password-stdin
    - docker-compose down || true
    - docker-compose pull
    - docker-compose up -d