stages:
  - build
  - push
  - deploy

variables:
  IMAGE_NAME: aestoolscelad/flask-app-baha:v4.0
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "/certs/client"

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=true", "--tlscert=/certs/server/cert.pem", "--tlskey=/certs/server/key.pem"]
  script:
    - docker system prune -f
    - docker compose build
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker compose push
  rules:
    - if: '$CI_COMMIT_MESSAGE !~ \[deploy\]/'
      when: on_success
    - when: never

deploy:
  stage: deploy
  image: docker:latest
  tags:
    - LocalRunner
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=true", "--tlscert=/certs/server/cert.pem", "--tlskey=/certs/server/key.pem"]
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker pull "$IMAGE_NAME"
    - docker stop mon-app || true
    - docker rm mon-app || true
    - docker compose up -d
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ \[deploy\]/'
      when: on_success


