stages:
  - build

build_image:
  stage: build
  tags:
    - LocalRunner
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/

    DOCKER_DRIVER: overlay2
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker-compose build
    - docker images


    #- docker push aestoolscelad/flask-app-baha:v4.0


