stages:
  - build
  - deploy

variables:
  IMAGE_NAME: aestoolscelad/flask-app-baha:v4.0
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker:latest
  tags:
    - windows-runner
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://localhost:2375
  before_script:
    - apk add --no-cache curl
    - sleep 30
  script:
    - docker info
    - docker system prune -f
    - docker compose build
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker compose push
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[build\]/'
      when: on_success
    - when: never

deploy:
  stage: deploy
  image: docker:latest
  tags:
    - windows-runner
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://localhost:2375
  before_script:
    - apk add --no-cache curl
    - sleep 30
  script:
    - docker info
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker compose down
    - docker pull "$IMAGE_NAME"
    - docker compose up -d --remove-orphans
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[deploy\]/'
      when: on_success
    - when: never
