stages:
  - build
  - deploy

variables:
  IMAGE_NAME: aestoolscelad/flask-app-baha:v4.0
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_HOST: tcp://host.docker.internal:2375

build:
  stage: build
  image: docker:24.0.7
  tags:
    - windows-runner
  before_script:
    - apk add --no-cache docker-compose
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

    - docker system prune -f
    - DOCKER_BUILDKIT=1 docker compose build --build-arg BUILDKIT_INLINE_CACHE=1
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .docker-cache/
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[build\]/'
      when: on_success
    - when: never

deploy:
  stage: deploy
  image: docker:24.0.7
  tags:
    - windows-runner
  before_script:
    - apk add --no-cache docker-compose
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker compose down
    - docker compose up -d --remove-orphans
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[deploy\]/'
      when: on_success
    - when: never

