stages:
  - build
  - push
  - deploy

variables:
  IMAGE_NAME: aestoolscelad/flask-app-baha:v4.0

build:
  stage: build
  tags:
    - windows-runner
  script:
    - echo "Build stage on Windows"
    - docker version
    - docker system prune -f
    - docker compose build
    - echo $Env:DOCKERHUB_PASSWORD | docker login -u $Env:DOCKERHUB_USERNAME --password-stdin
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[build\]/'
      when: on_success
    - when: never

deploy:
  stage: deploy
  tags:
    - windows-runner
  script:
    - echo "Deploy stage on Windows"
    - docker version
    - echo $Env:DOCKERHUB_PASSWORD | docker login -u $Env:DOCKERHUB_USERNAME --password-stdin
    - docker compose down
    - docker compose up -d --remove-orphans
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[deploy\]/'
      when: on_success
