stages:
  - build
  - push
  - deploy

variables:
  IMAGE_NAME: aestoolscelad/flask-app-baha:v4.0
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME .
    - docker save $IMAGE_NAME > image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 hour

push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  needs: ["build"]
  script:
    - docker load < image.tar
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push "$IMAGE_NAME"

deploy:
  stage: deploy
  tags:
    - LocalRunner
  needs: ["push"]
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker pull "$IMAGE_NAME"
    - docker stop mon-app || true
    - docker rm mon-app || true
    - docker run -d --name mon-app -p 5000:5000 "$IMAGE_NAME"