stages:
  - build
  - deploy
  - run
  - run2
  - test
  - fasktest

variables:
  IMAGE_NAME: aestoolscelad/flask-app-baha:v4.0


build:
  stage: build
  tags:
    - python-shell

  retry: 2
  script:
    - docker compose down

    - docker compose build
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[build\]/'
      when: on_success
    - when: never

deploy:
  stage: deploy
  tags:
    - python-shell

  retry: 2
  script:
    - docker compose down
    - docker compose up -d --remove-orphans
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[deploy\]/'
      when: on_success
    - when: never
run_flask_extern:
  stage: run
  tags:
    - python-shell


  before_script:
    - cd ServeurFlaskHost
    - python -m venv venv
    - venv\Scripts\Activate.ps1
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - Start-Process -NoNewWindow -FilePath "python" -ArgumentList "flaskhost.py"
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[run\]/'
      when: on_success

    - when: never

run_tests:
  stage: test
  tags:
    - python-shell


  before_script:
    - python -m venv venv
    - venv\Scripts\Activate.ps1
    - python -m pip install --upgrade pip
    - pip install robotframework
    - pip install requests
  script:
    - python execution.py
  retry: 2
  artifacts:
    paths:
      - results/Tests_*.zip
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[test\]/'
      when: on_success
    - when: never

run_flask_and_test:
  stage: run2
  tags:
    - python-shell
  variables:
    SHELL: "powershell"

  before_script:
    - cd ServeurFlaskHost
    - python -m venv venv
    - ./venv/Scripts/Activate.ps1
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install robotframework requests

  script:
    - |
      $flaskProcess = Start-Process -FilePath "python" -ArgumentList "flaskhost.py" -PassThru -NoNewWindow -RedirectStandardOutput "flask.log" -RedirectStandardError "flask_error.log"
      $flaskProcess.Id | Out-File flask_pid.txt
      Write-Host "Flask server started with PID $($flaskProcess.Id)."
      Start-Sleep -Seconds 5

      $resultatsPath = Join-Path $PWD.Path "resultats2"
      New-Item -ItemType Directory -Force -Path $resultatsPath
      
      Write-Host "Contenu initial du conteneur:"
      docker exec pfeproject-flask-1 ls -la /app
      
      docker exec pfeproject-flask-1 python execution.py --list MisesAJourAndReseau.robot 
      
      Write-Host "Contenu du dossier resultats dans le conteneur après les tests:"
      docker exec pfeproject-flask-1 ls -la /app/resultats

      Start-Sleep -Seconds 10
      
      Write-Host "Tentative de copie des fichiers depuis le conteneur..."
      Write-Host "Source: pfeproject-flask-1:/app/resultats/."
      Write-Host "Destination: $resultatsPath"
      docker cp pfeproject-flask-1:/app/resultats/. $resultatsPath
      
      if ($LASTEXITCODE -ne 0) {
        Write-Error "La commande 'docker cp' a échoué avec le code de sortie $LASTEXITCODE."
        exit 1
      }
      
      Write-Host "Contenu du dossier resultats2 après la copie:"
      Get-ChildItem -Path $resultatsPath -Recurse

  after_script:
    - |
      if (Test-Path -Path "ServeurFlaskHost/flask_pid.txt") {
        $pid = Get-Content "ServeurFlaskHost/flask_pid.txt"
        Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue
        Write-Host "Flask server with PID $pid stopped."
      }

  retry: 2
  artifacts:
    paths:
      - ServeurFlaskHost/resultats2/
      - ServeurFlaskHost/flask.log
      - ServeurFlaskHost/flask_error.log
    expire_in: 1 week
    when: always

  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[run2\]/'
      when: on_success
    - when: never