stages:
  - build
  - deploy

variables:
  IMAGE_NAME: aestoolscelad/flask-app-baha:v4.0
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://localhost:2375

build:
  stage: build
  image: docker:latest
  tags:
    - windows-runner
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false"]
      variables:
        DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache docker-compose
    - until docker info; do sleep 1; done
  script:
    - docker system prune -f
    - docker compose build --build-arg BUILDKIT_INLINE_CACHE=1
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .docker-cache/
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[build\]/'
      when: on_success
    - when: never

deploy:
  stage: deploy
  image: docker:latest
  tags:
    - windows-runner
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false"]
      variables:
        DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache docker-compose
    - until docker info; do sleep 1; done
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker compose down
    - docker compose up -d --remove-orphans
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[deploy\]/'
      when: on_success
    - when: never

