variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  # Add these for better DinD stability
  DOCKER_DRIVER: overlay2
  DOCKER_TLS: "false"  # Explicitly disable TLS if not using it

services:
  - name: docker:dind
    alias: docker
    command: ["--tls=false", "--host=tcp://0.0.0.0:2375"]  # Explicit configuration
build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker system prune -f
    - docker compose build
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker compose push
  rules:
    - if: '$CI_COMMIT_MESSAGE !~ /Mise à jour \[deploy\]/'
      when: on_success
    - when: never

deploy:
  stage: deploy
  image: docker:latest
  tags:
    - LocalRunner
  services:
    - name: docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker pull "$IMAGE_NAME"
    - docker stop mon-app || true
    - docker rm mon-app || true
    - docker compose up -d
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /Mise à jour \[deploy\]/'
      when: on_success
    - if: '$CI_COMMIT_MESSAGE !~ /Mise à jour \[deploy\]/'
      when: manual
