version: '3.8'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    image: aestoolscelad/flask-app-baha:v4.0
    ports:
      - "5000:5000"
      - "5037:5037"
      - "4724:4723"
      - "8201:8200"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - ADB_SERVER_SOCKET=tcp:host.docker.internal:5037
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
      - ANDROID_ADB_SERVER_PORT=5037
      - ANDROID_HOSTNAME=host.docker.internal:8201
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    privileged: true
    depends_on:
      - appium
    networks:
      - app-network

  appium:
    image: appium/appium
    container_name: appium
    environment:
      - ADB_SERVER_SOCKET=tcp:host.docker.internal:5037
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
      - ANDROID_ADB_SERVER_PORT=5037
      - ANDROID_HOSTNAME=host.docker.internal:8201
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "4723:4723"
      - "5037:5037"
      - "8201:8200"
    privileged: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
