version: '3.8'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    image: aestoolscelad/flask-app-baha:v4.0
    ports:
      - "5000:5000"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ADB_SERVER_SOCKET=tcp:host.docker.internal:5037
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
      - ANDROID_ADB_SERVER_PORT=5037
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - appium

  appium:
    image: appium/appium
    container_name: appium
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ADB_SERVER_SOCKET=tcp:host.docker.internal:5037
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
      - ANDROID_ADB_SERVER_PORT=5037
      - ANDROID_HOSTNAME=host.docker.internal:8201
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "4723:4723"
      - "8201:8200"
    privileged: true
