version: '3.8'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    image: aestoolscelad/flask-app-baha:v4.0
    network_mode: host
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ADB_SERVER_SOCKET=tcp:127.0.0.1:5037
      - ANDROID_ADB_SERVER_ADDRESS=127.0.0.1
      - ANDROID_ADB_SERVER_PORT=5037
      - ANDROID_HOSTNAME=127.0.0.1:8201
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    privileged: true
    depends_on:
      - appium


  appium:
    image: appium/appium
    container_name: appium
    network_mode: host
    environment:
      - ADB_SERVER_SOCKET=tcp:127.0.0.1:5037
      - ANDROID_ADB_SERVER_ADDRESS=127.0.0.1
      - ANDROID_ADB_SERVER_PORT=5037
      - ANDROID_HOSTNAME=127.0.0.1:8201
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true