version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    image: aestoolscelad/flask-app-baha:v4.0
    network_mode: host
    ports:
      - "5000:5000"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ${ANDROID_HOME:-$HOME/.android}:/root/.android
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - APPIUM_HOST=localhost
      - APPIUM_PORT=4723
    privileged: true
    depends_on:
      - appium

  appium:
    image: appium/appium
    container_name: appium
    network_mode: host
    ports:
      - "4723:4723"
      - "8201:8200"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ${ANDROID_HOME:-$HOME/.android}:/root/.android
    privileged: true
