version: '3.8'
services:
  flask:
    image: aestoolscelad/flask-app-baha:v3
    ports:
      - "5000:5000"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - ADB_SERVER_SOCKET=tcp:127.0.0.1:5037
      - ANDROID_ADB_SERVER_ADDRESS=127.0.0.1
      - ANDROID_ADB_SERVER_PORT=5037
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - appium
    network_mode: host



  appium:
    image: appium/appium
    container_name: appium
    environment:
      - ADB_SERVER_SOCKET=tcp:127.0.0.1:5037
      - ANDROID_ADB_SERVER_ADDRESS=127.0.0.1
      - ANDROID_ADB_SERVER_PORT=5037
      - ANDROID_HOSTNAME=127.0.0.1:8201
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - "4723:4723"
      - "8201:8200"  # Changed from 8200:8200

    privileged: true
    network_mode: bridge
