version: '3.8'
services:
  flask:
    image: aestoolscelad/flask-app-baha:v3.1
    ports:
      - "5000:5000"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ${ANDROID_HOME:-$HOME/.android}:/root/.android
    environment:
      - ADB_SERVER_SOCKET=tcp:host.docker.internal:5037
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
      - ANDROID_ADB_SERVER_PORT=5037
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - APPIUM_HOST=appium
      - APPIUM_PORT=4723
    privileged: true
    depends_on:
      - appium
    networks:
      - app-network

  appium:
    image: appium/appium
    container_name: appium
    environment:
      - ADB_SERVER_SOCKET=tcp:host.docker.internal:5037
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
      - ANDROID_ADB_SERVER_PORT=5037
      - ANDROID_HOSTNAME=host.docker.internal:8201
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ${ANDROID_HOME:-$HOME/.android}:/root/.android
    ports:
      - "4723:4723"
      - "8201:8200"
    privileged: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
