name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git config --global user.name "GITLAB_TOKEN"
          git config --global user.email "bahaeddine.Somrani@esprit.tn"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/bahaeddine.somrani1/PfeProject
          git push gitlab main
