name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get full history

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Mirror to GitLab
        run: |
          # Add GitLab remote
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/bahaeddine.somrani1/PfeProject.git
          # Direct push to GitLab, overwriting its history
          git push gitlab HEAD:main --force