name: Trigger GitLab Pipeline

on: [push]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        run: |
          curl -X POST \
            -H "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
            -F "ref=main" \
            https://gitlab.com/api/v4/projects/70183509/pipeline
